ImageCreditKeys = {
  "APi":"Andrea Piacquadio",
  "ARi":"Adhitya Rizky",
  "ARo":"Anni Roenkae",
  "BSo":"Bastien Sozu",
  "Cot":"Cottonbro",
  "DRo":"Dominika Roseclay",
  "DSh":"Daria Shevtsova",
  "EOD":"Elijah O'Donnell",
  "Ekr":"Ekrulila",
  "Ene":"Energepic",
  "KPl":"Kinetic Plasma",
  "KSu":"Ketut Subiyanto",
  "LMa":"Loannes Marc",
  "MVo":"Mehrad Vosoughi",
  "Meo":"Meowtch",
  "NSo":"Neto Soares",
  "Nih":"Nihilore",
  "Oct":"Octoptimist",
  "PZi":"Polina Zimmerman",
  "Pix":"Pixabay",
  "RSe":"Rafael Serafim",
  "SHa":"Suzy Hazelwood",
  "VSa":"Victoria Santos",
  "fau":"fauxels",
  "HLo":"Helena Lopes",
  "FCo":"Frank Cone",
  "ADR":"August de Richelieu",
  "QAHN":"Quang Anh Ha Nguyen",
  
  
  
};

/* Index 0: alt text Index 1: Source */
ImageAlts = {
  "apartment":["apartment", "Meo"],
  "bracelet":["bracelet", "Ene"],
  "cake":["cake", "Cot"],
  "ceo":["ceo", "DRo"],
  "cereal":["cereal", "ARi"],
  "convenience":["convenience", "MVo"],
  "couple":["couple", "DSh"],
  "cuddle0.0":["cuddle0.0", "KSu"],
  "cuddle0.1":["cuddle0.1", "KSu"],
  "cuddle0.2":["cuddle0.2", "KSu"],
  "ears":["ears", "PZi"],
  "frustration":["frustration", "Api"],
  "gold":["gold", "Pix"],
  "kiss":["kiss", "KSu"],
  "legs":["legs", "KSu"],
  "lingirie":["lingirie", "NSo"],
  "nuzzle":["nuzzle", "KSu"],
  "psychedelic":["psychedelic", "ARo"],
  "razor":["razor", "Cot"],
  "recovery":["recovery", "KSu"],
  "remorse":["remorse", "LMa"],
  "sandwich":["sandwich", "SHa"], 
  "sheep":["sheep", "Ekr"],
  "shooting":["shooting", "EOD"],
  "stairs":["stairs", "Oct"],
  "stuck":["stuck", "RSe"],
  "tablet":["tablet", "fau"],
  "tickle0.0":["tickle0.0", "KSu"],
  "tickle0.1":["tickle0.1", "KSu"],
  "tickle0.2":["tickle0.2", "KSu"],
  "traces":["traces", "KSu"],
  "washhands":["washhands", "VSa"],
  "money":["money", "Pix"],
  "watching":["watching", "KSu"],
  "laughing":["laughing", "HLo"],
  "universe":["universe", "FCo"],
  "flag":["flag", "ADR"],
  "jon":["Jon", "Pix"],
  "couple2":["Two women together.", "Api"],
  "bento":["bento", "QAHN"],
  
};